# Generated by Django 3.2.7 on 2021-09-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_module_1', '0002_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/uploads'),
        ),
    ]
